### ISSUE TITLE
Assign a keyboard shortcut key for "zoom to next"

### ISSUE THREAD

**Issue by TLDuhamel** [osm-nz/RapiD#2]
When adding addresses in the import, I typically click the Zoom To Next button to locate the next address to add. It would be a boost to efficiency to have a shortcut key for the zoom-to-next action.
Even better if the zoom-to-next action automatically selected the feature. However in this case the process runs the risk of becoming _too_ automated, losing the value of the manual oversight of the user.

**Comment by k-yle** [comment]
@TLDuhamel <kbd>G</kbd> should now select the next feature. Not sure if this is the best key to use but there are so many already in use. Any thoughts? I was thinking <kbd>4</kbd> or <kbd>Caps Lock</kbd> or re-purpose <kbd>F</kbd> (currently open settings)

Annoyingly, zoom-to-next goes to the next alphabetical feature not the next closest, but I think it'll be [too computationally expensive](https://en.wikipedia.org/wiki/Travelling_salesman_problem) to fix (unless I'm overthinking this...)

**Comment by TLDuhamel** [comment]
Wow thanks for your work, I've just tried it and it's really helpful.

We don't need to calculate an optimal route like travelling salesman, just want to find the next closest node. I think that doing a nearest neighbour (NN) algorithm shouldn't be too computationally expensive? Or is it.. I was quickly out of my depth reading into the algorithms.

Maybe the Haversine formula implemented here would do it: https://stackoverflow.com/questions/16774935/javascript-function-nearest-neighbor

**Comment by k-yle** [comment]
@TLDuhamel sorry for the delay, yes you're spot on, it's much simpler than I initially thought !

I've updated RapiD so that go-to-next will go the next closest feature to where you are on the map.
